services:
  frontend:
    container_name: robot-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://backend:8000
    ports:
      - "8080:80"

    environment:
      BACKEND_URL: http://backend:8000/

    networks:
      - robot_network

    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: robot-backend
    environment:
      NODE_ENV: production
      PORT: 8000
      JWT_SECRET_KEY: secret
      DATABASE_URL: postgresql://user:pass@database:5432/db
      REDIS_URL: redis://redis:6379/0
      BASE_ROBOT_API_URL: http://robot:5000
      CORS_ORIGINS: "*"

    networks:
      - robot_network

    depends_on:
      - database
      - redis
      - robot
  
  database:
    image: postgres:17-alpine
    volumes:
      - robot_postgres_database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

    networks:
      - robot_network

  redis:
    image: redis:8.6.1-alpine
    ports:
      - "6379:6379"

    networks:
      - robot_network
  
  robot:
    container_name: cmp9134_2526_robot
    image: ghcr.io/francescodelduchetto/cmp9134_2526_robotsim:latest
    ports:
      - "5555:5000"
    
    networks:
      - robot_network

networks:
  robot_network:

volumes:
  robot_postgres_database:

