services:
  mongo:
    image: mongo:7
    command: ["mongod", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - robot_mongo_data:/data/db

  redis:
    image: redis:8.6.1-alpine
    ports:
      - "6379:6379"

  robot:
    container_name: cmp9134_2526_robot
    image: ghcr.io/francescodelduchetto/cmp9134_2526_robotsim:latest
    ports:
      - "5555:5000"

volumes:
  robot_mongo_data:
